<a href="https://colab.research.google.com/github/adam-oberman/adam-oberman.github.io/blob/main/Math_462_Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

For Math 462, 2022 Fall, taught by Adam Oberman.

This notebook is based on [Jeff Calder](https://www-users.cse.umn.edu/~jwcalder/)'s 
- [Intro to Numpy](https://colab.research.google.com/drive/1mza3MOZEqBMtkLR33QAk4tGM17GivoKp?usp=sharing)
- see also [Calder's course](https://www-users.cse.umn.edu/~jwcalder/5467/index.html). 

This is a [Google Collab](https://research.google.com/colaboratory/faq.html) which allows you to run and share Python code in a browser.
This is convenient for teaching, because we don't have to install anything.  The Collab is (basically) a browser version of the Jupiter notebook https://jupyter.org/ which is fairly easy to install, and which can run directly on your computer. 

This notebook contains an introduction to [Numpy](https://numpy.org/), a fundamental pacakge for scientific computing in Python. For a more in-depth tutorial, see this [Numpy Tutorial](https://numpy.org/doc/stable/user/quickstart.html).





##Python Packages
The power of Python is due to the availability of many useful 3rd party packages. All packages must be explicitly imported in python code, and import statements normally go at the top of a python script. 

There are several ways to import packages. Below shows a few ways to import Numpy.

In [ ]:
import numpy
import numpy as np
from numpy import array
from numpy import sin

The second way "import numpy as np" is the most common. The "as np" gives a shortcut name "np" to numpy, to make coding easier. You can change the shortcut "np" to be anything you like. All functions within numpy have to be explicitly referenced with code like "numpy.array", "numpy.max", or "np.array" and "np.max", depending on how you imported numpy. 

The third option is used if you want to import just a single function from within Numpy (or another package). With the third option, you have only imported the function "array", and can use it without the "numpy" or "np" prefix. Nothing else from numpy is imported. The third option is almost never used with Numpy, but is often used for specialty packages when you only need to import a specific function.

Option 4: "from numpy import *" - this imports every numpy function so one doesn't need the "np." Generally this is not done for numpy since it is large - more conventional for smaller modules. Note the builtin sum command is overwritten with this command for numpy. Dangerous to do this with multiple packages at once- can confuse cross-listed functions. 

##Numpy arrays
The basic data type in Numpy is an array. 

###Initializing arrays
Arrays can have any number of dimensions, and can be initalized in a variety of ways. The code below shows how to initialize arrays a length 3 one-dimensional array in various ways.

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.ones(3)
c = np.zeros(4)
print(a)
print(b)
print(c)

[1 2 3]
[1. 1. 1.]
[0. 0. 0. 0.]


For multi-dimensional arrays, we simply add the sizes of the other dimensions. You can have as many dimensions as you like.

In [ ]:
import numpy as np

d = np.array([[1,2,3,4,5],[6,7,8,9,10]])  #2D array of size 2x5, initialized manually
e = np.ones((2,5))          #2D ones array of size 2x5
f = np.zeros((2,2))       #3D zeros array of size 2x5x8
g = np.random.rand(2,3,4)     #Random 3D array of size 2x8x4
print(d)
print(e)
print(f)
print(g)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[[0.44007795 0.06889    0.54648268 0.4596638 ]
  [0.13618765 0.27620552 0.95254988 0.86889673]
  [0.18630766 0.46155894 0.61324827 0.90035822]]

 [[0.32423368 0.88135451 0.59997323 0.02944828]
  [0.13393717 0.2420566  0.7663858  0.96642223]
  [0.46018915 0.31473194 0.00333657 0.02501844]]]


Most numpy construtors take a python tuple, i.e., the (2,5) on the second line above, as input. This is why there are two sets of brackets. This is not always the case, since we can see that np.random.rand takes multiple arguments instead of a python tuple. You will get used to this eventually.

The values of arrays are referenced with square brackets. Python starts with zero as the first index (contrary to, e.g., Matlab, which starts indexing at 1).

In [ ]:
import numpy as np

x = np.random.rand(2,3)
print(x)
print('first element', x[0,0])
print(x[0,1])
print(x[1,0])

x[0,0] = np.pi
print(x)

[[0.48120668 0.7192079  0.52158271]
 [0.92420681 0.53603755 0.88444813]]
first element 0.4812066751986339
0.7192078977407796
0.9242068119972584
[[3.14159265 0.7192079  0.52158271]
 [0.92420681 0.53603755 0.88444813]]


###Slicing arrays
It is often the case that you need to access only part of an array, say, a column of a matrix, or just the first few entries of a vector. Numpy has many useful ways to slice into arrays. Some examples of slicing rows or columns are below.

In [ ]:
import numpy as np

A = np.random.rand(5,3)
print(A)
print(A[:,0]) #First column of A
print(A[0,:]) #First row of A

[[0.81716594 0.09235818 0.92265302]
 [0.07626899 0.65146757 0.02654636]
 [0.18650458 0.8764487  0.01395849]
 [0.26581002 0.03277247 0.751429  ]
 [0.1983012  0.52806824 0.4059158 ]]
[0.81716594 0.07626899 0.18650458 0.26581002 0.1983012 ]
[0.81716594 0.09235818 0.92265302]


To extract only some of the entries in a given column or row of an array, the indexing notation "a:b:c" can be used. Generally this means start indexing at a, increment by c, and stop *before* you get to b. It is important to note that b is not included in the range of indexing. 

Some important points: If a is ommitted, it is taken as 0. If b is ommitted, the indexing goes to the end of the array. If any numbers are negative, the array is treated as periodic. Examples are given below. It is a good idea to master this type of indexing, as it is used very often in Numpy.

In [ ]:
import numpy as np

a = np.arange(19)
print(a)
#print(-a)
print(a[-a])
print(a[0:7])
print(a[7:])
print(a[10:-2])  #Note the -2 means 2 before the end of the array
print(a[::-5])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 0 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13 14 15 16 17 18]
[10 11 12 13 14 15 16]
[18 13  8  3]


We can mix the indexing above with slicing 2D or 3D arrays. 

In [ ]:
import numpy as np

A = np.reshape(np.arange(30),(3,10))
print(A)
print(A[:,::2])
print(A[0:2,:])
print(A[0,:])
print(A[:,3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[0 1 2 3 4 5 6 7 8 9]
[ 3 13 23]


###Logical indexing
It is often useful to index an array logically, by another true/false array. The code below draws a random array, and replaces any entry greater than $0.5$ with $10$, and all other entries are set to zero.

In [ ]:
import numpy as np

A = np.random.rand(2,5)
print(A)

I = A > 0.5  #Boolean true/false
print('the indices where condition holds')
print(I)
A[I] = 1.1
print('change the values at those indices')
print(A)
A[~I] = 0.1  #The ~ negates a boolean array
print('change the other values')
print(A)


[[0.9640684  0.53782486 0.6666711  0.21885204 0.83484165]
 [0.85968617 0.11308558 0.54015237 0.89684135 0.55314404]]
the indices where condition holds
[[ True  True  True False  True]
 [ True False  True  True  True]]
change the values at those indices
[[1.1        1.1        1.1        0.21885204 1.1       ]
 [1.1        0.11308558 1.1        1.1        1.1       ]]
change the other values
[[1.1 1.1 1.1 0.1 1.1]
 [1.1 0.1 1.1 1.1 1.1]]


It made sense to define I, which we were going to reference twice. If we only cared about one action based on values, we could do this all in one expression.

In [ ]:
B = np.random.rand(2,7)
print(B)

B[ B<.5 ] = 0 # B<0 still gives a boolean array; we just don't give it a name
print(B)

[[0.5624348  0.62756511 0.29683507 0.44893135 0.71589713 0.03608941
  0.58570959]
 [0.41382079 0.98158848 0.23884132 0.1301827  0.9758601  0.15751183
  0.20804572]]
[[0.5624348  0.62756511 0.         0.         0.71589713 0.
  0.58570959]
 [0.         0.98158848 0.         0.         0.9758601  0.
  0.        ]]


###Operations on Numpy arrays
The advantage of using Numpy arrays instead of Python lists is that Numpy contains very efficient implementations of common operations (e.g., matrix/vector multiplication) with Numpy arrays. These operations are executed with highly optimized compiled C-code.

The code below shows the advantage of using Numpy operations instead of basic Python. This is just for adding two arrays; the difference becomes far larger for more complicated operations, like matrix/vector operations. The moral of this example is to try an "vectorize" all your Numpy code, using built in Numpy functions, instead of using loops.

In [ ]:
import numpy as np
import time

#Let's make two long lists that we wish to add elementwise
n = 100000
A = n*[1]
B = n*[2]
print('A=',end='');print(A)
print('B=',end='');print(B)

#Let's add A and B elementwise using a loop in Python
start_time = time.time()
C = n*[0]
for i in range(n):
    C[i] = A[i] + B[i]
python_time_taken = time.time() - start_time
print('C=',end='');print(C)
print("Python took %s seconds." % python_time_taken)

#Let's convert to Numpy and add using Numpy operations
A = np.array(A)
B = np.array(B)

start_time = time.time()
C = A + B
numpy_time_taken = time.time() - start_time
print("Numpy took %s seconds." % (numpy_time_taken))

print('Numpy was %f times faster.'%(python_time_taken/numpy_time_taken))


A=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

As you can see in the code above, the operation $+$ in Numpy adds two arrays elementwise. The operation $-$ is the same for subtraction. The operation $*$ multiplies two arrays of the same size elementwise, and is *not* matrix multiplication. To perform matrix multiplication, use $@$ in Numpy. Matrices must have compatible sizes to perform matrix multiplication. Some examples are below.

In [ ]:
import numpy as np

A = np.random.rand(3,5)
B = np.random.rand(3,5)

print('A*B=',end='');print(A*B)  #elementwise multiplication
print('A-B=',end='');print(A-B)  #elementwise subtraction

#Examples of matrix multiplication and matrix/vector multiplication
print('A@B.T=',end='');print(A@B.T)   #B.T means the transpose of B
C = np.random.rand(5,7)
D = np.ones((5,))
print('A@C=',end='');print(A@C)
print('A@D=',end='');print(A@D)

A*B=[[0.10219808 0.39052358 0.24566411 0.00383407 0.14535912]
 [0.81275578 0.01211755 0.15571985 0.26354223 0.00802798]
 [0.08388383 0.63706194 0.06507469 0.38795714 0.18276466]]
A-B=[[-0.09767688  0.34512924 -0.1208774  -0.41279461  0.52276329]
 [-0.03148835 -0.2121259  -0.66631889  0.22894741  0.20073646]
 [-0.26738635 -0.31582092  0.16833699 -0.15312957  0.74754327]]
A@B.T=[[0.88757895 0.86576626 1.14960489]
 [0.77200819 1.25216339 0.97686425]
 [1.00000811 0.89842456 1.35674227]]
A@C=[[1.4017532  1.63233285 1.41233812 1.71016312 1.43724751 1.43498835
  1.07549609]
 [1.38852198 1.56269139 0.63187772 0.93135794 1.31561966 1.76240723
  1.05370634]
 [1.90088702 1.77748735 1.52662207 1.88191344 1.59839925 1.96654991
  1.18603293]]
A@D=[2.26702887 1.99136421 2.68643781]


**Warning**: There are some situations in Python where $*$ can refer to matrix/vector multiplication, and this can easily be confusing. We will not see this often (if ever), but it arises when one uses matrix data types, instead of numpy arrays. There are matrix data types in Numpy and Scipy. See examples below. I prefer to use only Numpy arrays and use @ for matrix multiplication, so it is always clear what operation is intended.

In [ ]:
import numpy as np
import scipy.sparse as sparse

A = np.random.rand(3,3)
x = np.random.rand(3,1)

print(A@x)
print(A*x)

A = np.matrix(A)
print(A*x)

A = sparse.csr_matrix(A)
print(A*x)

[[0.25217869]
 [0.80808243]
 [0.81985295]]
[[0.02548842 0.18872314 0.03324456]
 [0.0784849  0.26047668 0.15974093]
 [0.56360668 0.21531499 0.49412613]]
[[0.25217869]
 [0.80808243]
 [0.81985295]]
[[0.25217869]
 [0.80808243]
 [0.81985295]]


Most other operations work fine with Numpy arrays, and work elementwise. This includes the power operation $**$, and any special functions in Numpy. Some examples are below.

In [ ]:
import numpy as np

A = np.reshape(np.arange(10),(2,5))

print(A)
print(A**2) #Square all elements in A
print(np.sin(A)) #Apply sin to all elements of A

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]
[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]]


Finally, there are many useful functions in Numpy for computing with arrays, that is, finding the mean or median value of each column, summing all the entries in a matrix, finding the norm of the matrix, etc. Pretty much any function you may want to apply to a matrix has a built-in Numpy function to do the job, and as per the discussion above, this is much faster than writing a loop to do it in Python. Examples below.

In [ ]:
import numpy as np

A = np.reshape(np.arange(30),(3,10))

print(A)
print(np.sum(A))   #Sums all entries in A
print(np.sum(A,axis=0))  #Gives sums along axis=0, so it reports column sums
print(np.sum(A,axis=1))  #Row sums

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
435
[30 33 36 39 42 45 48 51 54 57]
[ 45 145 245]


In the code above, experiment with replacing "sum" by "mean" or "median".

###Broadcasting
When operating on numpy arrays, it is sometimes useful to perform elementwise operations on two arrays of different sizes. Say, you want to add a vector to every row of a matrix. Numpy broadcasts automatically, as long as the sizes of the last dimensions match up.

In [ ]:
import numpy as np

A = np.reshape(np.arange(30),(3,10))
print(A)

x = np.ones((10,))
print(x.shape)
print(A+x) #Adds the row vector of all ones to each row of A
print(A+1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
(10,)
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


Suppose we wanted to add a column vector to each column of A. The code below fails, why?

In [ ]:
import numpy as np

A = np.reshape(np.arange(30),(3,10))
print(A)

x = np.ones((3,))
print(x)
print(A+x) #Adds the row column of all ones to each row of A


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[1. 1. 1.]


ValueError: ignored

Answer: For broadcasting, the sizes of the last dimensions must match up. Above they are 10 and 3, which are not compatible, whereas in the first example they were 10 and 10. To fix this, you can add a dummy axis to x, to make the last dimensions match up, using np.newaxis.

In [ ]:
print(x)
print(x[:,None])
print(x.shape)
print(x[:,None].shape)
print(A+x[:,None])
print(A+A[:,0][:,None])

[1. 1. 1.]
[[1.]
 [1.]
 [1.]]
(3,)
(3, 1)
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


##Exercises
These exercises should be completed using just the basic operations in Numpy. In particular, do not use the np.linalg package.
1. Write a Python function that computes the square root of a positive number using the Babylonian method. The Babylonian method to compute $\sqrt{S}$ for $S>0$ constructs the sequence $x_n$ by setting $x_0=S$ and iterating
$$x_{n+1} = \frac{1}{2}\left(x_n + \frac{S}{x_n}\right).$$
Your code can take as input a tolerance parameter $\varepsilon>0$, and should iterate until $|x_n^2 - S| \leq \varepsilon$, and then return $x_n$. Test your square root function to make sure it works.
2. Write a function that computes the largest magnitude eigenvalue of a square matrix with the power iteration. The power iteration is
$$x_{n+1} = \frac{Ax_n}{\|A x_n\|}.$$
For a diagonalizable matrix, the iteration converges to the eigenvector of $A$ with largest magnitude eigenvalue. The eigenvalue is 
$$\lambda = \lim_{n\to \infty}x_n^TAx_n.$$
Compare your function to the true eigenvector and eigenvalue for small matrices where you can compute it by hand, to check that your function works.
3. Write a function that numerically approximates $\pi$ via the integral expression
$$\pi = 4\int_0^1 \sqrt{1-x^2} \, dx.$$
Your function should not use any loops. Use a Numpy array and Numpy functions instead. The code cell below will get you started, you only have to replace the ?? by your formula for numerical integration. Then you can change dx to be as small as you like to get higher accuracy. How many decimal places of $\pi$ can you accurately compute? You should approximate the integral by a Riemann sum
$$\pi \approx 4\sum_{i=1}^n \sqrt{1-x_i^2}\Delta x,$$
where $\Delta x = 1/n$.

In [ ]:
import numpy as np

dx = 1e-8
x = np.arange(0,1,dx)
approx_pi = 4*np.sum(np.sqrt(1-x**2)*dx)
print(approx_pi)
print(np.pi)
print(np.log10(abs(approx_pi-np.pi)))

3.141592673588603
3.141592653589793
-7.698995851720683


In [ ]:
#Hints for Problem 2
import numpy as np

#Generate a random symmetric matrix
A = np.random.rand(2,2)
A = A@A.T
print(A)

#Generate a random vector of length 2
x = np.random.rand(2)
print(x)

#Multiply Ax
y = A@x
print(y)

#Compute the norm ||y||
norm = np.sqrt(y.T@y)
print(norm)

[[0.22674898 0.27351125]
 [0.27351125 0.55322113]]
[0.55177381 0.93684357]
[0.3813514 0.669198 ]
0.7702303927645293
